import { put } from '@vercel/blob/client';
import { apiClient } from './apiClient';
import { DocumentProcessingResult } from '../types/document';
import { ReviewResolutionRequest } from '../types/review';
import { UploadTokenData, UploadMode } from '../types/api';

export type BlobUploadResult = Awaited<ReturnType<typeof put>>;

export const DIRECT_UPLOAD_MAX_MB = Number(import.meta.env.VITE_DIRECT_UPLOAD_MAX_MB) || 4;
export const MAX_UPLOAD_SIZE_MB = Number(import.meta.env.VITE_MAX_UPLOAD_SIZE_MB) || 25;
export const DIRECT_UPLOAD_MAX_BYTES = DIRECT_UPLOAD_MAX_MB * 1024 * 1024;
export const MAX_UPLOAD_SIZE_BYTES = MAX_UPLOAD_SIZE_MB * 1024 * 1024;

export interface HybridProcessOptions {
  onUploadProgress?: (percentage: number) => void;
  onModeSelected?: (mode: UploadMode) => void;
  onStageChange?: (stage: string) => void;
  signal?: AbortSignal;
}

export const documentService = {
  /**
   * Returns current configured upload thresholds in megabytes and bytes.
   */
  getThresholds() {
    return {
      directMaxMb: DIRECT_UPLOAD_MAX_MB,
      maxUploadSizeMb: MAX_UPLOAD_SIZE_MB,
      directMaxBytes: DIRECT_UPLOAD_MAX_BYTES,
      maxSizeBytes: MAX_UPLOAD_SIZE_BYTES,
    };
  },

  /**
   * Requests a short-lived client upload token from the backend for large files.
   * Calls POST /api/v1/documents/upload-token with Authorization: Bearer <accessToken>.
   */
  async getUploadToken(filename: string, signal?: AbortSignal): Promise<UploadTokenData> {
    return apiClient.post<UploadTokenData>(
      '/api/v1/documents/upload-token',
      { filename },
      signal
    );
  },

  /**
   * Directly uploads the file to private Vercel Blob from the browser using the official
   * client upload token generated by the backend. Never requires or handles server secrets.
   */
  async uploadToBlob(
    token: string,
    pathname: string,
    file: File,
    options?: {
      onProgress?: (percentage: number) => void;
      signal?: AbortSignal;
    }
  ): Promise<BlobUploadResult> {
    return put(pathname, file, {
      access: 'public',
      token,
      abortSignal: options?.signal,
      onUploadProgress: (progress) => {
        if (options?.onProgress && progress.percentage !== undefined) {
          options.onProgress(Math.round(progress.percentage));
        }
      },
    });
  },

  /**
   * Triggers document processing for a file previously uploaded to Vercel Blob.
   * Calls POST /api/v1/documents/process with JSON body containing the safe blobPathname.
   */
  async processDocumentFromBlob(
    blobPathname: string,
    filename: string,
    signal?: AbortSignal
  ): Promise<DocumentProcessingResult> {
    return apiClient.post<DocumentProcessingResult>(
      '/api/v1/documents/process',
      { blobPathname, filename },
      signal
    );
  },

  /**
   * Direct multipart upload for small files (<= direct threshold).
   * Calls POST /api/v1/documents/process with multipart/form-data.
   */
  async processDocumentDirect(
    file: File,
    signal?: AbortSignal
  ): Promise<DocumentProcessingResult> {
    const formData = new FormData();
    formData.append('file', file, file.name);

    return apiClient.postFormData<DocumentProcessingResult>(
      '/api/v1/documents/process',
      formData,
      signal
    );
  },

  /**
   * Hybrid PDF processing pipeline:
   * - Validates file exists, has size > 0, and size <= 25 MB.
   * - If size <= DIRECT_UPLOAD_MAX_BYTES (default 4 MB): routes directly via multipart.
   * - If size > DIRECT_UPLOAD_MAX_BYTES and <= 25 MB: acquires client upload token,
   *   uploads directly to private Vercel Blob with progress tracking, and passes
   *   the safe Blob pathname to the processing endpoint.
   * - Converges to the exact same DocumentProcessingResult.
   */
  async processDocumentHybrid(
    file: File,
    options?: HybridProcessOptions
  ): Promise<DocumentProcessingResult> {
    // 1. Validation checks
    if (!file || file.size === 0) {
      throw new Error('The selected file appears to be empty.');
    }

    if (file.size > MAX_UPLOAD_SIZE_BYTES) {
      throw new Error(`File is too large. Maximum supported PDF size is ${MAX_UPLOAD_SIZE_MB} MB.`);
    }

    // 2. Route selection
    if (file.size <= DIRECT_UPLOAD_MAX_BYTES) {
      options?.onModeSelected?.('direct');
      options?.onStageChange?.('Uploading PDF document buffer...');
      return this.processDocumentDirect(file, options?.signal);
    }

    // 3. Blob Path for large files
    options?.onModeSelected?.('blob');
    options?.onStageChange?.('Authorizing secure cloud upload...');

    let tokenData: UploadTokenData;
    try {
      tokenData = await this.getUploadToken(file.name, options?.signal);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Unknown authorization error';
      throw new Error(`Failed to authorize secure upload: ${msg}`);
    }

    options?.onStageChange?.('Uploading PDF document...');
    try {
      await this.uploadToBlob(tokenData.clientToken, tokenData.blobPathname, file, {
        onProgress: options?.onUploadProgress,
        signal: options?.signal,
      });
    } catch (err: unknown) {
      if (err instanceof Error && (err.name === 'AbortError' || err.message.includes('cancelled') || err.message.includes('aborted'))) {
        throw err;
      }
      const msg = err instanceof Error ? err.message : 'Cloud storage upload failed';
      throw new Error(`Cloud upload failed: ${msg}`);
    }

    options?.onStageChange?.('Processing PDF document...');
    return this.processDocumentFromBlob(tokenData.blobPathname, file.name, options?.signal);
  },

  /**
   * Backwards-compatible processing method (delegates to hybrid pipeline).
   */
  async processDocument(
    file: File,
    options?: HybridProcessOptions
  ): Promise<DocumentProcessingResult> {
    return this.processDocumentHybrid(file, options);
  },

  /**
   * Submits user review decisions for discrepancies or ambiguous values,
   * receiving an updated backend-authoritative result.
   */
  async submitReview(
    payload: ReviewResolutionRequest,
    signal?: AbortSignal
  ): Promise<DocumentProcessingResult> {
    return apiClient.post<DocumentProcessingResult>(
      '/api/v1/documents/review',
      payload,
      signal
    );
  },

  /**
   * Requests the real binary XLSX spreadsheet for a processed document.
   * Calls POST /api/v1/documents/download with Authorization: Bearer <accessToken>,
   * handles the response as a real XLSX binary file, and returns both the binary Blob
   * and the backend-provided filename (ending with .xlsx).
   */
  async downloadXlsx(
    xlsxBase64: string,
    filename?: string,
    signal?: AbortSignal
  ): Promise<{ blob: Blob; filename: string }> {
    const defaultName = filename || 'financial_report.xlsx';
    const result = await apiClient.postBlob(
      '/api/v1/documents/download',
      {
        xlsxBase64,
        filename: defaultName,
      },
      signal
    );

    let resolvedFilename = result.filename || defaultName;
    if (!resolvedFilename.toLowerCase().endsWith('.xlsx')) {
      resolvedFilename = `${resolvedFilename}.xlsx`;
    }

    return {
      blob: result.blob,
      filename: resolvedFilename,
    };
  },
};
